### ISSUE TITLE
dont download it you will be hacked

### ISSUE THREAD

**Issue by Ammitte** [m41k1n4177/BurpSuite#2]

**Comment by Ammitte** [comment]
please dont download it you will be hacked

**Comment by m41k1n4177** [comment]
you downloaded exe? lol this is written in original repo:

> It is recommended that you compile the launcher yourself from the source code of the launcher and write the java parameters required for startup in the command line. The compiled version currently provided is from a long time ago.

will leave it up but add small warning

**Comment by m41k1n4177** [comment]
solved by [a6418b6](https://github.com/m41k1n4177/BurpSuite/commit/a6418b6e08cac6dbd0009a6f1dfc3454b39771c2)
closes #2

**Comment by m41k1n4177** [comment]
my mistake, exe from portswigger-cdn.net has same md5 & sha256 values as the release on portswigger.net. you were't hacked from any DLd exe that was on the original or on my translated repo, but being on windows doesn't help, probably ur own fault.

linux loader is clean and i've been using it for a year or two

![image](https://github.com/m41k1n4177/BurpSuite/assets/106442797/6a3e7435-8427-4796-a145-bef407e0e2d9)
